### ISSUE TITLE
Cannot render CocosSharpView at all in Xamarin.Forms

### ISSUE THREAD

**Issue by matt5005** [mono/CocosSharp#407]
I'm having an issue using the very basis of CocosSharp - rendering with Xamarin.Forms. Having CC in version 1.7.1 and Xamarin 2.3.2.127.
ViewCreated event is not called at all for my CocosSharpView (either created from code, or from xaml). What is more, direct casting to CCGameView throws compilation error:

![image](https://cloud.githubusercontent.com/assets/23627649/20474016/97e007c4-afc4-11e6-878a-e4cf6ed9a117.png)

**Comment by zahik** [comment]
Same problem to me on Android (Didn't check IOS)
A working game with XF 2.0 worked with CC 1.7.1. but when upgrade to XF 2.3.2.127 Black screen on android and ViewCreated is not fired.
????

**Comment by lmarques6** [comment]
Same issue with me for UWP. Using Xamarin 2.3.4.247 and CocosSharp 1.7.1 . CocosSharpView.ViewCreated event fires when debugging Android but not when debugging UWP.

**Comment by kolbma** [comment]
I'm seeing the same problem. I'm currently trying to make CocosSharp.Forms UWP aware.
Do you have any idea if it works in WindowsPhone8?
Where is the event fired? Can we see how it is done on working platform?

**Comment by kolbma** [comment]
Have you tried with Xamarin.Forms 2.5.0.280555? Because stuff works for me on Android.
